// Generated by `yarn sb:db:types` when local Supabase is running.
// Placeholder until migrations exist and types are regenerated.
export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
